### ISSUE TITLE
Tabelog can not be accessed from heroku

### ISSUE THREAD

**Issue by dtaniwaki** [dtaniwaki/hubot-tabelog#1]
Although I checked I can use this scripts in my local environment and remote server, it seems I can not make http requests from heroku server to Tabelog.

**Comment by dtaniwaki** [comment]
It's fixed with this change.
https://github.com/dtaniwaki/hubot-tabelog/commit/ad6b59f9b56dada1302c49e69928f5313c5a1d10

**Comment by mcfiredrill** [comment]
Why do you need a proxy?

**Comment by dtaniwaki** [comment]
Because Tabelog doesn't accept any access from AWS including Heroku. Where are you trying to use hubot?

**Comment by dtaniwaki** [comment]
You can just pick up a proxy from [here](http://www.getproxy.jp/).
:)
